@baseUrl = http://localhost:3001

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "johh Doe",
  "email": "johh@example.com",
  "cpf": "62516387024",
  "birthDate": "2000-01-01"
}

###

# @name retrieve_acount
GET {{baseUrl}}/accounts/41553189035

###

# @name list_acounts
GET {{baseUrl}}/accounts


###

# @name list_acounts_paginated
GET {{baseUrl}}/accounts?page=1&perPage=3


