version: '3.8'

services:
  postgres:
    container_name: igma-database
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/infra/database/migration/db.sql:/docker-entrypoint-initdb.d/migrate.sql

volumes:
  db:
    driver: local