version: '3.8'

services:
  postgres:
    container_name: igma-database
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}